### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by lukedirtwalker** [monebag/monorepo-diff-buildkite-plugin#105]
Hi @chronotc,

Thanks for the great work on this very useful plugin.

Unfortunately I have a few issues with the plugin, which would already be addressed by PRs. Specifically I think about
- https://github.com/chronotc/monorepo-diff-buildkite-plugin/pull/85
- https://github.com/chronotc/monorepo-diff-buildkite-plugin/pull/102

But there are others as well. It seems none of them got any feedback.
Are you still maintaining this project?
Otherwise it would be cool to have some indication on the repo that you are looking for maintainers, or that a fork should be created.

Thanks a lot for any feedback.

**Comment by chronotc** [comment]
Hey @lukedirtwalker,

Sorry for the extremely late response  
I'm not actively maintaining this project. 
It's been difficult testing these changes as I no longer use most of the features offered by this plugin day to day.
I'm open for additional maintainers, especially those who are actively using the plugin.

**Comment by adikari** [comment]
@lukedirtwalker In an effort to continue maintaining the project, @chronotc has decided to transfer it over to me. The repo will be under the new org structure which will allow us to better manage future contributors, maintainers and permission of the project. 

For now, I will try my best to keep the project alive. Please understand that I will be working on this in my free time which I have very less of.

I will be opening positions for project maintainers to existing contributors to the project at some point soon.

**Comment by lukedirtwalker** [comment]
Thanks a lot for the clarification.
