### ISSUE TITLE
ERROR: unsupported architecture "amd64"

### ISSUE THREAD

**Issue by jhfoo** [monebag/monorepo-diff-buildkite-plugin#128]
WHAT:
Tried to run the plugin on Buildkite agent on a FreeBSD. The agent works for all Buildkite commands. Returns above error message.

CONFIG:
- FreeBSD on a x64 AMD CPU
- OS: 13.1-RELEASE
- Shell: Bash

**Comment by adikari** [comment]
Can you pls provide the output of `uname -s` and `uname -m` from your machine.

**Comment by jhfoo** [comment]
```
# uname -s 
FreeBSD

# uname -m
amd64
```

**Comment by adikari** [comment]
Thanks. I will fix this as soon as I have some time

**Comment by jhfoo** [comment]
TIA! I'm trying to use some complex workaround for now but it's not scalable.

**Comment by adikari** [comment]
@jhfoo sorry for the delayed action on this. I got busy with other things. The issue what that we are not currently generating binaries for free bsd. The linked PR generates binaries for FreeBSD and 2 other bsd distros. 
Once the PR is released, please use the latest version of the plugin and see if that fixes your problem.

I don't have a FreeBSD machine to test with but this should resolve the issue.

**Comment by jhfoo** [comment]
Appreciate the effort. I'll monitor the pr and test for you.

**Comment by adikari** [comment]
It's all released. Let me know how you go

**Comment by jhfoo** [comment]
Thanks for spending some time on this. I switched back to 2.5.8 on your suggestion and got the same error:
```
ERROR: unsupported architecture "amd64"
```

[Pipeline](https://buildkite.com/kungfoo/monorepo-test/builds/4#01872128-184e-4a2a-88fc-1c8f19fdd43f)

**Comment by jhfoo** [comment]
Which timezone are you in? I can pair with you to test until it is fixed.

**Comment by jhfoo** [comment]
Can you open this issue? Doesn't look fixed.
