### ISSUE TITLE
make it possible to run this plugin using a fork

### ISSUE THREAD

**Issue by vgrigoruk** [monebag/monorepo-diff-buildkite-plugin#129]
We've forked this repo, but we can not run this plugin from out, as it fails to initialise due to this hardcoded string:
https://github.com/peakon/monorepo-diff-buildkite-plugin/blob/master/plugin.go#L11

It would be nice if there is a way to customise GITHUB_ORG in that URL via env var.

**Comment by adikari** [comment]
@vgrigoruk thank you for your interest in using the plugin. 

Given that you have a fork of the repo, should not it be easy for you to update the plugin name to match your repo in your fork?

I would add this functionality if there were multiple people interested in doing the same thing but that is not the primary use case of this plugin.  

For now, I will close this issue. If you really want this functionality I am happy for you to create a PR.
