### ISSUE TITLE
Support passing `meta_data` in build trigger

### ISSUE THREAD

**Issue by iaroslav-ciupin** [monebag/monorepo-diff-buildkite-plugin#133]
Buildkite supports passing `meta_data` in trigger step https://buildkite.com/docs/pipelines/trigger-step#trigger-step-attributes. Looks like plugin currently doesn't support this.

**Comment by adikari** [comment]
I will add this soon

**Comment by iaroslav-ciupin** [comment]
@adikari thank you very much!
