### ISSUE TITLE
How to allow a triggered pipeline to fail?

### ISSUE THREAD

**Issue by giorgenes** [monebag/monorepo-diff-buildkite-plugin#79]
I'm triggering a pipeline with custom env variables that I would like to allow to soft_fail so it doesn't fail my parent pipeline. Is there a way to do that?

Thanks in advance!

**Comment by adikari** [comment]
@giorgenes You can try the soft_fail to see if it works. I have not tested it before but I think it should work. Let me know how you go. https://buildkite.com/changelog/56-command-steps-can-now-be-made-to-soft-fail

**Comment by giorgenes** [comment]
@adikari I tried but it seems to be removed from the plugin output. Also buildkite docs don't mention usage with trigger

**Comment by adikari** [comment]
@giorgenes makes sense. Might need to update the plugin to generate pipeline with the flag. I will mark this as a enhancement and hopefully can add at some point. Feel free to send a PR if you like.

**Comment by adikari** [comment]
`soft_fail` is not supported
