### ISSUE TITLE
[Question] how to display stderr from diff command

### ISSUE THREAD

**Issue by Looooopy** [monebag/monorepo-diff-buildkite-plugin#94]
Older versions of this plugin (1.x) would show stderr output from the diff command in buildkite but its now hidden.
Is there some way to  turn it on again or do i need to pipe it to a file?

**Comment by adikari** [comment]
@Looooopy you can try using `log_level` configuration. https://github.com/monebag/monorepo-diff-buildkite-plugin#log_level-optional
